apiVersion: 1

datasources:
- name: Loki
  type: loki
  access: proxy
  url: http://localhost:3100
  basicAuth: true
  basicAuthUser: my_user
  jsonData:
    maxLines: 1000
    derivedFields:
    - datasourceUid: my_jaeger_uid
      matcherRegex: "traceID=(\\w+)"
      name: TraceID
      url: '$${__value.raw}'
      urlDisplayLabel: 'View Trace'

    - matcherRegex: "traceID=(\\w+)"
      name: TraceID
      url: 'http://localhost:16686/trace/$${__value.raw}'
  secureJsonData:
    basicAuthPassword: test_password

- name: Prometheus
  type: prometheus
  access: proxy
  url: http://localhost:9090
  isDefault: true
  jsonData:
    timeout: 60
    maxLines: 1000

- name: Jaeger
  type: jaeger
  url: http://jaeger-tracing-query:16686/
  access: proxy
  uid: my_jaeger_uid
